---
deployment:
  tasks:
    - export REPOPATH=/home2/pavelpo1/repositories/build/*
    - export SITEPATH=/home2/pavelpo1/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
