export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SHOW_MODAL = "PORTFOLIO/SHOW_MODAL";
export const HIDE_MODAL = "PORTFOLIO/HIDE_MODAL";
export const CLEAN_MODAL = "PORTFOLIO/CLEAN_MODAL";
export const POSITION_MODAL = "PORTFOLIO/POSITION_MODAL";
